In [6]:
import numpy as np 
import pandas as pd 
import os
import re
import string
import numpy as np 
import random
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
# from plotly import graph_objs as go
# import plotly.express as px
# import plotly.figure_factory as ff
from collections import Counter

from PIL import Image
# from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator


import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

from tqdm import tqdm
import os
import nltk
# import spacy
import random

In [7]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Lusiana\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [8]:
def clean_text(text):
    '''Make text lowercase, remove text in square brackets,remove links,remove punctuation
    and remove words containing numbers.'''
    text = str(text).lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*', '', text)
    return text

In [9]:
df = pd.read_csv("spam.csv", encoding="latin-1")

df = df.dropna(how="any", axis=1)
df.columns = ['target', 'message']

df.head()

target                                            message
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [10]:
df['message_len'] = df['message'].apply(lambda x: len(x.split(' ')))
df.head()

target                                            message  message_len
0    ham  Go until jurong point, crazy.. Available only ...           20
1    ham                      Ok lar... Joking wif u oni...            6
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...           28
3    ham  U dun say so early hor... U c already then say...           11
4    ham  Nah I don't think he goes to usf, he lives aro...           13

In [11]:
df['message_clean'] = df['message'].apply(clean_text)
df.head()

target                                            message  message_len  \
0    ham  Go until jurong point, crazy.. Available only ...           20   
1    ham                      Ok lar... Joking wif u oni...            6   
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...           28   
3    ham  U dun say so early hor... U c already then say...           11   
4    ham  Nah I don't think he goes to usf, he lives aro...           13   

                                       message_clean  
0  go until jurong point crazy available only in ...  
1                            ok lar joking wif u oni  
2  free entry in  a wkly comp to win fa cup final...  
3        u dun say so early hor u c already then say  
4  nah i dont think he goes to usf he lives aroun...

In [12]:
stop_words = stopwords.words('english')
more_stopwords = ['u', 'im', 'c']
stop_words = stop_words + more_stopwords

def remove_stopwords(text):
    text = ' '.join(word for word in text.split(' ') if word not in stop_words)
    return text
    
df['message_clean'] = df['message_clean'].apply(remove_stopwords)
df.head()

target                                            message  message_len  \
0    ham  Go until jurong point, crazy.. Available only ...           20   
1    ham                      Ok lar... Joking wif u oni...            6   
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...           28   
3    ham  U dun say so early hor... U c already then say...           11   
4    ham  Nah I don't think he goes to usf, he lives aro...           13   

                                       message_clean  
0  go jurong point crazy available bugis n great ...  
1                              ok lar joking wif oni  
2  free entry  wkly comp win fa cup final tkts  m...  
3                      dun say early hor already say  
4        nah dont think goes usf lives around though

In [13]:
stemmer = nltk.SnowballStemmer("english")

def stemm_text(text):
    text = ' '.join(stemmer.stem(word) for word in text.split(' '))
    return text

In [14]:
df['message_clean'] = df['message_clean'].apply(stemm_text)
df.head()

target                                            message  message_len  \
0    ham  Go until jurong point, crazy.. Available only ...           20   
1    ham                      Ok lar... Joking wif u oni...            6   
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...           28   
3    ham  U dun say so early hor... U c already then say...           11   
4    ham  Nah I don't think he goes to usf, he lives aro...           13   

                                       message_clean  
0  go jurong point crazi avail bugi n great world...  
1                                ok lar joke wif oni  
2  free entri  wkli comp win fa cup final tkts  m...  
3                      dun say earli hor alreadi say  
4          nah dont think goe usf live around though

In [15]:
def preprocess_data(text):
    # Clean puntuation, urls, and so on
    text = clean_text(text)
    # Remove stopwords
    text = ' '.join(word for word in text.split(' ') if word not in stop_words)
    # Stemm all the words in the sentence
    text = ' '.join(stemmer.stem(word) for word in text.split(' '))
    
    return text

In [16]:
df['message_clean'] = df['message_clean'].apply(preprocess_data)
df.head()

target                                            message  message_len  \
0    ham  Go until jurong point, crazy.. Available only ...           20   
1    ham                      Ok lar... Joking wif u oni...            6   
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...           28   
3    ham  U dun say so early hor... U c already then say...           11   
4    ham  Nah I don't think he goes to usf, he lives aro...           13   

                                       message_clean  
0  go jurong point crazi avail bugi n great world...  
1                                ok lar joke wif oni  
2  free entri  wkli comp win fa cup final tkts  m...  
3                        dun say ear hor alreadi say  
4          nah dont think goe usf live around though

In [17]:
df.head(-5)

target                                            message  message_len  \
0       ham  Go until jurong point, crazy.. Available only ...           20   
1       ham                      Ok lar... Joking wif u oni...            6   
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...           28   
3       ham  U dun say so early hor... U c already then say...           11   
4       ham  Nah I don't think he goes to usf, he lives aro...           13   
...     ...                                                ...          ...   
5562    ham  Ok lor... Sony ericsson salesman... I ask shuh...           18   
5563    ham                                Ard 6 like dat lor.            5   
5564    ham  Why don't you wait 'til at least wednesday to ...           15   
5565    ham                                       Huh y lei...            3   
5566   spam  REMINDER FROM O2: To get 2.50 pounds free call...           28   

                                          message_clean  
0     go jurong point crazi avail bugi n great world...  
1                                   ok lar joke wif oni  
2     free entri  wkli comp win fa cup final tkts  m...  
3                           dun say ear hor alreadi say  
4             nah dont think goe usf live around though  
...                                                 ...  
5562  ok lor soni ericsson salesman ask shuhui say q...  
5563                                  ard  like dat lor  
5564             dont wait til least wednesday see get   
5565                                            huh lei  
5566  remind  get  pound free call credit detail gre...  

[5567 rows x 4 columns]

In [18]:
texts = df

In [19]:
texts = df['message_clean']

# GLOVE

In [20]:
!pip install Tokenizer  

In [23]:
pip install keras

Note: you may need to restart the kernel to use updated packages.


In [25]:
pip install tensorflow

  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Using cached termcolor-1.1.0.tar.gz (3.9 kB)
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
  Using cached tensorboard_data_server-0.6.1-py3-none-any.whl (2.4 kB)
  Using cached google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
  Using cached rsa-4.8-py3-none-any.whl (39 kB)
  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4829 sha256=0645a38655e4aff8b4a539d65badf32fbd4b92cf226f5aba54d53453aa999108
  Stored in directory: c:\users\lusiana\appdata\local\pip\cache\wheels\a0\16\9c\5473df82468f958445479c59e784896fa24f4a5fc024b0f501
Successfully built termcolor
Note: you may need to restart the kernel to use updated packages.


In [26]:
import keras

In [27]:
# Calculate the length of our vocabulary
from keras.preprocessing.text import Tokenizer
word_tokenizer = Tokenizer()

In [28]:
word_tokenizer.fit_on_texts(texts)

vocab_length = len(word_tokenizer.word_index) + 1
vocab_length

6726

In [29]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Lusiana\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [30]:
import tensorflow as tf
def embed(corpus): 
    return word_tokenizer.texts_to_sequences(corpus)

In [31]:
longest_train = max(texts, key=lambda sentence: len(word_tokenize(sentence)))
length_long_sentence = len(word_tokenize(longest_train))

train_padded_sentences = tf.keras.preprocessing.sequence.pad_sequences(
    embed(texts), 
    length_long_sentence, 
    padding='post'
)

X = train_padded_sentences

In [32]:
X

array([[   2, 3179,  274, ...,    0,    0,    0],
       [   8,  236,  527, ...,    0,    0,    0],
       [   9,  356,  588, ...,    0,    0,    0],
       ...,
       [6724, 1002, 6725, ...,    0,    0,    0],
       [ 138, 1251, 1603, ...,    0,    0,    0],
       [1986,  378,  170, ...,    0,    0,    0]])

# TFIDF

In [33]:
frame = df

In [34]:
doc_id = []
for i in range(1, (len(frame['message_clean']))+1):
  doc_id.append('D' + str(i))

In [35]:
frame['docID'] = doc_id
frame.head(5)

target                                            message  message_len  \
0    ham  Go until jurong point, crazy.. Available only ...           20   
1    ham                      Ok lar... Joking wif u oni...            6   
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...           28   
3    ham  U dun say so early hor... U c already then say...           11   
4    ham  Nah I don't think he goes to usf, he lives aro...           13   

                                       message_clean docID  
0  go jurong point crazi avail bugi n great world...    D1  
1                                ok lar joke wif oni    D2  
2  free entri  wkli comp win fa cup final tkts  m...    D3  
3                        dun say ear hor alreadi say    D4  
4          nah dont think goe usf live around though    D5

# TFIDF with TFIDF Vectorization

## Kode dibawah ini digunakan pada TFiDF Group
Tidak digunakan pada TF-IDF non group karena membutuhkan waktu > 4 jam 

In [36]:
def term_document_matrix(data, vocab= None, document_index= 'ID', text= 'text'):
    """Calculate frequency of term in the document.
    
    parameter: 
        data: DataFrame. 
        Frequency of word calculated against the data.
        
        vocab: list of strings.
        Vocabulary of the documents    
        
        document_index: str.
        Column name for document index in DataFrame passed.
        
        text: str
        Column name containing text for all documents in DataFrame,
        
    returns:
        vocab_index: DataFrame.
        DataFrame containing term document matrix.
        """
    
    vocab_index = pd.DataFrame(columns=df[document_index], index= vocab).fillna(0)
    
    for word in vocab_index.index:
        
        for doc in data[document_index]:
            
            freq = data[data[document_index] == doc][text].values[0].count(word)
            vocab_index.loc[word,doc] = freq
    
    return vocab_index

In [37]:
# menghitung jumlah kata di dalam dataset

new_all_text = " ".join(frame['message_clean'].apply(clean_text).values)
vocab = []
vocab = np.unique(word_tokenize(new_all_text))
vocab = [word for word in vocab if word not in stopwords.words('english')]

In [ ]:
# dapat dijalankan namun butuh waktu lama, sekitaran 4 jam untuk dataset ini

similarity_index = ''
similarity_index = term_document_matrix(frame,vocab,'docID','message_clean')
similarity_index

In [37]:
similarity_index.sum(axis= 1)

aa    42
dtype: int64

In [ ]:
sum

In [34]:
# bergantung pada term_document_matrix
def tf_idf_score(vocab_index, document_index, inv_df= 'inverse_document_frequency'):
    """
    Calculate tf-idf score for vocabulary in documents
    
    parameter:
        vocab_index: DataFrame.
        Term document matrix.
        
        document_index: list or tuple.
        Series containing document ids.
        
        inv_df: str.
        Name of the column with calculated inverse document frequencies.
        
    returns:
        vocab_index: DataFrame.
        DataFrame containing term document matrix and document frequencies, inverse document frequencies and tf-idf scores
    """
    total_docx = len(document_index)
    vocab_index['document_frequency'] = vocab_index.sum(axis= 1)
    vocab_index['inverse_document_frequency'] = np.log2( total_docx / vocab_index['document_frequency'])
    
    for word in vocab_index.index:
        
        for doc in document_index:
            
                tf_idf = np.log2(1 + vocab_index.loc[word,doc]) * np.log2(vocab_index.loc[word][inv_df])
                vocab_index.loc[word,'tf_idf_'+doc] = tf_idf
    
    return vocab_index

In [35]:
similarity_index = tf_idf_score(similarity_index, df.docID.values)
similarity_index

docID  D1  D2  D3  D4  D5  D6  D7  D8  D9  D10  ...  tf_idf_D5563  \
aa      0   0   0   0   0   0   0   0   0    0  ...           0.0   

docID  tf_idf_D5564  tf_idf_D5565  tf_idf_D5566  tf_idf_D5567  tf_idf_D5568  \
aa              0.0           0.0           0.0           0.0           0.0   

docID  tf_idf_D5569  tf_idf_D5570  tf_idf_D5571  tf_idf_D5572  
aa              0.0           0.0           0.0           0.0  

[1 rows x 11146 columns]

In [ ]:
similarity_index.to_csv('term_doc_matrix.csv')

In [ ]:
# test= pd.read_csv('term_doc_matrix.csv')
# test = test.set_index('Unnamed: 0')

In [ ]:
# def query_processing(query):
#     """
#     Pre-processing query to accomodate calculations for tf-idf score
    
#     parameter:
#         query: str.
#         Textual query input to the system.
        
#     returns:
#         query: str.
#         Cleaned string.
#         """
#     query= re.sub('\W',' ',query)
#     query= query.strip().lower()
#     query= " ".join([word for word in query.split() if word not in stopwords.words('english')])
    
#     return query

In [ ]:
tfidfscoreingroup_a = tfidf_long

In [32]:
tfidfscoreingroup_a.to_csv('term_doc_matrix.csv')

In [ ]:
test= pd.read_csv('term_doc_matrix.csv')
test = test.set_index('Unnamed: 0')

In [ ]:
test.variable

Unnamed: 0
4803           aa
7033          aah
9827          aah
10895         aah
12722       aaniy
            ...  
37445211       ûò
37445312       ûò
37445561       ûò
37448643       ûò
37453549    ûówel
Name: variable, Length: 44239, dtype: object

In [ ]:
def query_score(vocab_index, query):
    """
    Calculate tf-idf score for query terms
    
    parameter:
        vocab_index: DataFrame.
        Term document matrix with inverse document frequency and term frequencies calculated.
        
        query: str.
        Query submitted to the system
        
    returns:
        vocab_index: DataFrame.
        Term document matrix with tf-idf scores for terms per document and query terms.
    """
    for word in np.unique(query.split()):
        
        freq = query.count(word)
        
        if [vocab_index[variable].astype(str).str.contains(word, na=False) for variable in vocab_index]:
            print('true')
            tf_idf = np.log2(1+freq) * np.log2(vocab_index.loc[word].inverse_document_frequency)
            import pdb
            pdb()
            vocab_index.loc[word,"query_tf_idf"] = tf_idf
            vocab_index['query_tf_idf'].fillna(0, inplace=True)
    
    return vocab_index

In [ ]:
# if [test[variable].astype(str).str.contains("aa", na=False) for variable in test]:
#   print('true')
# else:
#   print('false')

true


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from nltk.corpus import stopwords

train_set = frame.message_clean #Documents
test_set = ["aa aaooooright canteen woman"] #Query
stopWords = stopwords.words('english')

In [ ]:
vectorizer = CountVectorizer(stop_words = stopWords)
transformer = TfidfTransformer()

trainVectorizerArray = vectorizer.fit_transform(train_set).toarray()
testVectorizerArray = vectorizer.transform(test_set).toarray()

print('Fit Vectorizer to train set')
print(trainVectorizerArray)
print('Transform Vectorizer to test set')
print(testVectorizerArray)

transformer.fit(trainVectorizerArray)
print(transformer.transform(trainVectorizerArray).toarray())

transformer.fit(testVectorizerArray)

tfidf = transformer.transform(testVectorizerArray)
print(tfidf.todense())

Fit Vectorizer to train set
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Transform Vectorizer to test set
[[1 0 0 ... 0 0 0]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0.5 0.  0.  ... 0.  0.  0. ]]


In [ ]:
def cosine_similarity(vocab_index, document_index, query_scores):
    """
    Calculates cosine similarity between the documents and query
    
    parameter:
        
        vocab_index: DataFrame.
        DataFrame containing tf-idf score per term for every document and for the query terms.
        
        document_index: list.
        List of document ids.
        
        query_scores: str.
        Column name in DataFrame containing query term tf-idf scores.
        
    returns:
        cosine_scores: Series.
        Cosine similarity scores of every document.
    """
    cosine_scores = {}
    
    query_scalar = np.sqrt(sum(vocab_index[query_scores] ** 2))
    
    for doc in document_index:
        
        doc_scalar = np.sqrt(sum(vocab_index[doc] ** 2))
        dot_prod = sum(vocab_index[doc] * vocab_index[query_scores])
        cosine = (dot_prod / (query_scalar * doc_scalar))
        
        cosine_scores[doc] = cosine
        
    return pd.Series(cosine_scores)

In [ ]:
cosines = cosine_similarity(similarity_index, df.docID.values, 'query_tf_idf')
cosines

In [ ]:
def retrieve_index(data,cosine_scores, document_index):
    """
    Retrieves indices for the corresponding document cosine scores
    
    parameters:
        data: DataFrame.
        DataFrame containing document ids and text.
        
        cosine_scores: Series.
        Series containing document cosine scores.
        
        document_index: str.
        Column name containing document ids in data.
        
    returns:
        data: DataFrame.
        Original DataFrame with cosine scores added as column.
    """
    
    data = data.set_index(document_index)
    data['scores'] = cosine_scores
    
    return data.reset_index().sort_values('scores',ascending=False).head(10).index

In [ ]:
indices = retrieve_index(df, cosines, 'docID')
indices